### ISSUE TITLE
Release laser_proc into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/laser_proc#10]
Would you mind releasing `laser_proc` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 16 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by jonbinney** [comment]
I'll take a quick look now to see if it compiles on noetic. looks like there is no python code in this package, so i think changing the cmake required version should be the only change needed.

**Comment by jonbinney** [comment]
Updated the cmake version; otherwise seems to compile fine on noetic. Released: https://github.com/ros/rosdistro/pull/24558
