### ISSUE TITLE
Resquest for kinetic release

### ISSUE THREAD

**Issue by doisyg** [ros-perception/laser_proc#2]

**Comment by d130s** [comment]
+1

This blocks https://github.com/ros-drivers/urg_node/issues/21

**Comment by jonbinney** [comment]
@chadrockey do you mind if i release this repo for kinetic?

**Comment by 130s** [comment]
Thanks to @tfoote it's done https://github.com/ros/rosdistro/pull/12807 :)

**Comment by jonbinney** [comment]
Oh, yay! Thanks @tfoote !

**Comment by tfoote** [comment]
it didn't need any updates so i released it
