### ISSUE TITLE
Lunar and Melodic releases

### ISSUE THREAD

**Issue by tonybaltovski** [ros-perception/laser_proc#4]
Please and thank you!

**Comment by jonbinney** [comment]
@chadrockey want me to release this?

**Comment by tonybaltovski** [comment]
Friendly ping @chadrockey and hopefully it goes to the right email now.

**Comment by chadrockey** [comment]
I can see mentions now!  I'll queue this up for release.

**Comment by chadrockey** [comment]
Done.

**Comment by tonybaltovski** [comment]
Thanks @chadrockey !
