### ISSUE TITLE
Request for ROS2 branches

### ISSUE THREAD

**Issue by Karsten1987** [ros-perception/laser_proc#5]
I would like to request the creation of branches for ROS2 development.
In particular, I am interested in having a `dashing-devel` and general `ros2-devel`. We have to port for `laser_proc` available for dashing under [here](https://github.com/bosch-robotics-na/laser_proc) and would like to open a PR to a ROS2 branch on this upstream repo and have it released from here ideally.

**Comment by dirk-thomas** [comment]
@chadrockey FYI

**Comment by chadrockey** [comment]
Thanks @dirk-thomas !

@Karsten1987 I invited you to this repo, you should be able to create the branches you need and handle the ROS2 side for now.

Thanks!

**Comment by clalancette** [comment]
Given that these branches have been created now, I'm going to close this out.
